### PR TITLE
http: Allow configuration of the URI from /new

### PR DESCRIPTION
**Pull request by jedsmith**
This patch adds a new flag, `--host`, which permits runtime
configuration of the URI returned by the `/new` handler. The default
behavior is the current hardcoded behavior, which always directs clients
to https://discovery.etcd.io.

Example usage:

    bin/discovery.etcd.io --host=https://discovery.example.com

The given string will be used verbatim and is not parsed. It is
completely possible to return malformed URIs if not careful.

Future work should perhaps react to the Host header, but further study
is needed regarding the ELB CoreOS uses in production; at the very
least, TLS should be preferred, so the Host header might not always be
the best default for this purpose.

Fixes: #3
Cc: @brianredbeard

### CODE REVIEW

**Comment by jedsmith** [comment]
(Note to #16, #18, #21, and #24 that I did see your approaches before writing this, and wasn't ignoring them. I just *personally* think it's better with a flag and will debate both approaches.)

**Comment by philips** [comment]
Hrm, I really want to make sure there is no double or trailing slash. Should be an easy bytes.TrimRight([]byte(host), "/")

**Comment by jedsmith** [comment]
Added in 02f16ff.

**Comment by philips** [comment]
lgtm, we can deal with the other stuff later. Merging.

**Comment by philips** [comment]
other stuff being env variables, configurable etcd server, etc.

**Comment by jedsmith** [comment]
Yeah, that was my thought, too. We should overhaul a lot, but too much for one PR.

**Pull request merged**
